version: '3'

services:
  web:
    build: .docker/php
    container_name: app-phpfpm
    depends_on:
      - db
    volumes:
      - ./:/app
      - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  nginx:
    image: nginx:1.18-alpine
    container_name: app-webserver
    ports:
      - 5000:8000
    volumes:
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    depends_on:
      - web

  db:
    image: mariadb:10.5
    container_name: app-db
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_USERNAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
      
  redis:
    container_name: app-redis
    restart: on-failure    
    image: redis:4-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data      
      
  ws-server:
    image: node:12-alpine
    container_name: app-ws-server
    entrypoint: ["npm", "run", "ws-server-start"]    
    working_dir: /app
    ports:
      - 6001:6001    
    volumes:
      - ./:/app       
      
  npm:
    image: node:12-alpine
    container_name: app-npm
    #entrypoint: ['npm']
    working_dir: /app
    volumes:
      - ./:/app           

volumes:
  db-data:
  redis-data:  
